# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d196a1621acd5ff4aa4e7ae898a762077caef4e83d416a4656252176d5215a82c6b1b18c1c9169b50c3bbadb676f19694fe2c395dcc39624c6ec7277d916ab24

test:
  secret_key_base: 61a4bb1ffbe622c84a3612b324518dfccfb1fbea32d7aa70946ff5664a81f621ccb770e72fe760067ac12a30bc3eb9df797d4ecc6ad90d03d92959b555d56ca9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
